apiVersion: v1
name: suricata
home: https://github.com/sealingtech/EDCOP
version: 0.7.9
description: EDCOP Suricata Chart
details:
  This Chart provides an inline Suricata daemonset for use with the EDCOP project.
icon: https://idsips.files.wordpress.com/2015/10/suri-400x400.png

